name: Deploy CINEXA to Azure Web App

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A71BEC944CBB4F33BCF63E657AD68EAF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DCCC383A8F0648E9A6D067D3B7A1DC66 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_152C47291CC24DE79A33C5F1D49EB70D }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: cinexa
          package: .
